### ISSUE TITLE
Request for contributing information

### ISSUE THREAD

**Issue by adamjanovsky** [jsrojas/FlowLabeler#1]
Hi, 

I've bumbed into this repository via your [Kaggle dataset](https://www.kaggle.com/jsrojas/labeled-network-traffic-flows-114-applications) that is simply awesome. I have a plan to slightly expand the dataset with flows of my own class. That may be a generally handy functionality, in case anyone is interested in adding his own classes. 

I noticed couple of errors in the repository, I've improved the code quality on my local copy and I'd like to share the results. I'm wondering if you have any contributing policy in mind? Should I create a pull request? Should I just fork and work on my own copy? What would be the preferred way in your opinion?

**Comment by jsrojas** [comment]
Hello adamjanovsky

First of all I want to thank you for your interest and your kind words about the Kaggle dataset. I just realized I haven't specified the contribution policies, I will update that.

For now, regarding your contribution, I ask you to please do the following:
 
- Create a fork of the repository via HTTPS with the commands:
                                                  `git clone https://github.com/YOUR-USERNAME/FlowLabeler.git`
                                          `git remote add upstream https://github.com/YOUR-USERNAME/FlowLabeler.git`

- Implement all the changes and new functionalities you have come up with in your fork.
- Verify everything is working correctly on your new version.
- Do the pull request to review the changes.

Once again thank you for your interest and let me know if you have any other doubt.

Best regards.

**Comment by adamjanovsky** [comment]
Hi,

thanks a lot for your swift response. As clarified in the mails, I'll probably go for [nfstream](https://www.nfstream.org) instead of flowLabeler. With that being said, I unfortunately won't spend the time on finishing my adjustments and making the contribution. 

Please, feel free to close the issue as you well documented the contribution guidelines.

**Comment by jsrojas** [comment]
Hello again.

No worries, I thought it would be better for you to focus on nfstream instead. Either way thanks again for your interest and good luck with your work.
